inherit_mode:
  merge:
    - Exclude
    - IgnoredPatterns

inherit_gem:
  radius-spec: common_rubocop_rails.yml

AllCops:
  Exclude:
    - 'bin/console'
    - 'bin/setup'
    - 'bin/update'
    - 'bin/yri'
    - 'bin/yardoc'
    - 'Rakefile'

Layout/AlignHash:
  Enabled: false
